"""Python side of the cross-language golden-file drift guard.

tests/fixtures/golden_scenarios.json was generated by actually running
model/scenario.py and friends (see scripts/generate_golden_scenarios.py) -
this test re-runs the same functions and confirms Python's output still
matches the recorded fixture (a standard snapshot/regression test).

The JS side (tests/js/test_golden_scenarios.mjs) checks the SAME fixture
against the ported JavaScript implementation in web/static/calculator.js -
that is the test that actually catches Python/JS drift. This Python test
mostly guards against an accidental Python regression changing behaviour
without the fixture being regenerated deliberately.

If a change to model/scenario.py is intentional, regenerate the fixture:
    python3 scripts/generate_golden_scenarios.py
and update web/static/calculator.js to match before committing.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from ontario_home_energy_futures.model.collective_purchasing import (
    CollectiveTier,
    apply_collective_purchase,
)
from ontario_home_energy_futures.model.cost_of_inaction import (
    DecisionCostInputs,
    calculate_cost_of_inaction,
)
from ontario_home_energy_futures.model.decline import bill_component_after_years
from ontario_home_energy_futures.model.financing import (
    QuoteComponents,
    amortize_loan,
    apply_group_discount,
)
from ontario_home_energy_futures.model.net_metering import NetMeteringLedger
from ontario_home_energy_futures.model.scenario import (
    DeclineScenario,
    PriceScenario,
    evaluate_grid_only,
    evaluate_solar_purchase,
)
from ontario_home_energy_futures.model.solar import (
    SolarSystemInputs,
    calculate_annual_monthly_production_kwh,
)
from ontario_home_energy_futures.model.waiting import find_breakeven_decline_rate

REPO_ROOT = Path(__file__).parent.parent.parent
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "golden_scenarios.json"

PRICE_SCENARIOS = {
    "reference": PriceScenario(
        id="reference", label="Reference", electricity_energy_real=0.015,
        fixed_delivery_real=0.020, variable_delivery_real=0.010, general_inflation=0.020,
    ),
    "stress": PriceScenario(
        id="stress", label="Stress", electricity_energy_real=0.050,
        fixed_delivery_real=0.050, variable_delivery_real=0.045, general_inflation=0.020,
    ),
}
DECLINE_SCENARIOS = {
    "flat": DeclineScenario(id="flat", label="Flat", real_annual_installed_cost_change=0.0),
    "moderate": DeclineScenario(id="moderate", label="Moderate", real_annual_installed_cost_change=0.02),
}
REFERENCE_QUOTE = QuoteComponents(
    panels=6720, inverter=2100, racking=1680, electrical_equipment=1260,
    labour=4200, design_and_engineering=630, permitting=420,
    utility_connection=840, installer_overhead=3150,
)


@pytest.fixture(scope="module")
def fixture_data():
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def _run_scenario_case(case: dict):
    inputs = dict(case["inputs"])
    if case["function"] == "evaluate_grid_only":
        inputs["price_scenario"] = PRICE_SCENARIOS[inputs["price_scenario"]]
        return evaluate_grid_only(**inputs)
    elif case["function"] == "evaluate_solar_purchase":
        inputs["price_scenario"] = PRICE_SCENARIOS[inputs["price_scenario"]]
        inputs["decline_scenario"] = DECLINE_SCENARIOS[inputs["decline_scenario"]]
        inputs["base_quote"] = QuoteComponents(**inputs["base_quote"])
        return evaluate_solar_purchase(**inputs)
    raise ValueError(f"unknown function {case['function']!r}")


def test_fixture_file_exists_and_has_cases(fixture_data):
    assert len(fixture_data["scenario_cases"]) >= 5
    assert len(fixture_data["standalone_cases"]) >= 5


@pytest.mark.parametrize("case_index", range(7))
def test_scenario_case_matches_fixture(fixture_data, case_index):
    case = fixture_data["scenario_cases"][case_index]
    result = _run_scenario_case(case)
    expected = case["expected"]

    assert result.label == expected["label"]
    assert result.purchase_year_offset == expected["purchase_year_offset"]
    assert result.initial_cost_cad == pytest.approx(expected["initial_cost_cad"], abs=0.01)
    assert result.financing_interest_cad == pytest.approx(expected["financing_interest_cad"], abs=0.01)
    assert result.group_discount_cad == pytest.approx(expected["group_discount_cad"], abs=0.01)
    assert result.total_nominal_cad == pytest.approx(expected["total_nominal_cad"], abs=0.01)
    assert result.total_present_value_cad == pytest.approx(expected["total_present_value_cad"], abs=0.01)
    assert result.simple_payback_years == expected["simple_payback_years"]

    assert len(result.annual_cash_flows) == len(expected["annual_cash_flows"])
    for actual_flow, expected_flow in zip(result.annual_cash_flows, expected["annual_cash_flows"]):
        assert actual_flow.year == expected_flow["year"]
        assert actual_flow.total_nominal_cad == pytest.approx(expected_flow["total_nominal_cad"], abs=0.01)
        assert actual_flow.total_present_value_cad == pytest.approx(expected_flow["total_present_value_cad"], abs=0.01)


def test_bill_component_after_years_matches_fixture(fixture_data):
    case = fixture_data["standalone_cases"]["bill_component_after_years"]
    result = bill_component_after_years(**case["inputs"])
    assert list(result) == pytest.approx(case["expected"], abs=0.0001)


def test_apply_group_discount_matches_fixture(fixture_data):
    case = fixture_data["standalone_cases"]["apply_group_discount"]
    quote = QuoteComponents(**case["inputs"]["quote"])
    result = apply_group_discount(quote, case["inputs"]["discount_fraction"])
    for key, value in case["expected"].items():
        assert getattr(result, key) == pytest.approx(value, abs=0.01)


def test_amortize_loan_matches_fixture(fixture_data):
    case = fixture_data["standalone_cases"]["amortize_loan"]
    result = amortize_loan(**case["inputs"])
    for key, value in case["expected"].items():
        assert getattr(result, key) == pytest.approx(value, abs=0.01)


def test_solar_production_matches_fixture(fixture_data):
    case = fixture_data["standalone_cases"]["solar_production"]
    inputs = case["inputs"]
    system = SolarSystemInputs(
        capacity_kw_dc=inputs["capacity_kw_dc"], orientation=inputs["orientation"], shading=inputs["shading"],
        degradation_annual=inputs["degradation_annual"], inverter_efficiency=inputs["inverter_efficiency"],
        other_system_losses=inputs["other_system_losses"],
    )
    result = calculate_annual_monthly_production_kwh(
        system,
        regional_monthly_yield_kwh_per_kw={
            1: 62, 2: 82, 3: 118, 4: 132, 5: 148, 6: 150,
            7: 152, 8: 138, 9: 112, 10: 82, 11: 52, 12: 48,
        },
        orientation_factors={"south": 1.00, "southeast": 0.96, "southwest": 0.96, "east": 0.85, "west": 0.85, "north": 0.65},
        shading_factors={"none": 1.00, "light": 0.95, "moderate": 0.85, "heavy": 0.65},
        system_age_years=inputs["system_age_years"],
    )
    for month_str, expected_kwh in case["expected"].items():
        assert result[int(month_str)] == pytest.approx(expected_kwh, abs=0.01)


def test_net_metering_ledger_matches_fixture(fixture_data):
    case = fixture_data["standalone_cases"]["net_metering_ledger_two_months"]
    ledger = NetMeteringLedger(export_credit_rate_cad_per_kwh=case["inputs"]["export_credit_rate_cad_per_kwh"])
    actual_months = []
    for month_input in case["inputs"]["months"]:
        r = ledger.process_month(**month_input)
        actual_months.append({
            "period": r.period, "exported_kwh": r.exported_kwh, "grid_import_kwh": r.grid_import_kwh,
            "credit_created_cad": r.credit_created_cad, "credit_used_cad": r.credit_used_cad,
            "credit_expired_cad": r.credit_expired_cad, "credit_closing_balance_cad": r.credit_closing_balance_cad,
        })
    for actual, expected in zip(actual_months, case["expected"]["months"]):
        for key in ("exported_kwh", "grid_import_kwh", "credit_created_cad", "credit_used_cad"):
            assert actual[key] == pytest.approx(expected[key], abs=0.01)
    assert ledger.effective_value_per_generated_kwh() == pytest.approx(
        case["expected"]["effective_value_per_generated_kwh"], abs=0.0001
    )


def test_find_breakeven_decline_rate_matches_fixture(fixture_data):
    case = fixture_data["standalone_cases"]["find_breakeven_decline_rate"]
    common_purchase_kwargs = dict(
        base_annual_bill_cad=8400.0, price_scenario=PRICE_SCENARIOS["reference"], base_quote=REFERENCE_QUOTE,
        tax_rate=0.13, down_payment_fraction=1.0, annual_interest_rate=0.079, loan_term_years=10,
        horizon_years=20, discount_rate=0.04, fixed_share=0.30, variable_share=0.15, energy_share=0.55,
        annual_grid_bill_after_solar_cad=2940.0, annual_maintenance_cad=150.0,
        inverter_replacement_year=12, inverter_replacement_cost_cad=1800.0,
        annual_credits_used_cad=2520.0, total_credits_expired_cad=0.0,
        total_solar_generation_kwh=9000.0, total_grid_imports_kwh=3360.0,
    )

    def npv_cost_for_rate(rate: float) -> float:
        ds = DeclineScenario(id="sweep", label="sweep", real_annual_installed_cost_change=rate)
        result = evaluate_solar_purchase(
            label="sweep", purchase_year_offset=case["inputs"]["wait_years_offset"],
            group_discount_fraction=0.0, is_cash=True, decline_scenario=ds, **common_purchase_kwargs,
        )
        return result.total_present_value_cad

    breakeven = find_breakeven_decline_rate(
        npv_cost_for_decline_rate=npv_cost_for_rate, npv_cost_buy_now=case["inputs"]["npv_cost_buy_now"]
    )
    assert breakeven == pytest.approx(case["expected"], abs=0.0001)


@pytest.mark.parametrize("case_name", ["apply_collective_purchase_group_10", "apply_collective_purchase_group_20_capped"])
def test_apply_collective_purchase_matches_fixture(fixture_data, case_name):
    case = fixture_data["standalone_cases"][case_name]
    tier_dict = case["inputs"]["tier"]
    tier = CollectiveTier(
        id=tier_dict["id"], label=tier_dict["label"], households=tier_dict["households"],
        reductions=tier_dict["reductions"], overall_discount_cap_percent=tier_dict["overall_discount_cap_percent"],
    )
    result = apply_collective_purchase(tier=tier, base_costs_by_component=case["inputs"]["base_costs_by_component"])
    expected = case["expected"]
    assert result.total_reduced_cost == pytest.approx(expected["total_reduced_cost"], abs=0.01)
    assert result.total_reduction_cad == pytest.approx(expected["total_reduction_cad"], abs=0.01)
    assert result.effective_discount_percent == pytest.approx(expected["effective_discount_percent"], abs=0.001)
    assert result.capped == expected["capped"]


def test_calculate_cost_of_inaction_matches_fixture(fixture_data):
    case = fixture_data["standalone_cases"]["calculate_cost_of_inaction_three_decisions"]
    inputs = [DecisionCostInputs(**d) for d in case["inputs"]["decisions"]]
    results = calculate_cost_of_inaction(inputs)
    for label, expected in case["expected"].items():
        actual = results[label]
        assert actual.additional_nominal_cost_cad == pytest.approx(expected["additional_nominal_cost_cad"], abs=0.01)
        assert actual.additional_present_value_cad == pytest.approx(expected["additional_present_value_cad"], abs=0.01)
        assert actual.grid_electricity_purchased_while_waiting_kwh == pytest.approx(
            expected["grid_electricity_purchased_while_waiting_kwh"], abs=0.01
        )
        assert actual.solar_generation_forgone_kwh == pytest.approx(expected["solar_generation_forgone_kwh"], abs=0.01)
